#ifndef __TDK_LAYOUT_OBJECT_TYPES_H
#define __TDK_LAYOUT_OBJECT_TYPES_H

typedef enum LAYOUT_TYPES
{
	LT_UNDEFINED=-1,
	LT_LINE=0,
	LT_RECTANGLE=1,
	LT_ELLIPSE=2,
	LT_IMAGE=3,
	LT_TEXT=4,
	LT_SCALE=5,
	LT_NORTH=6,
	LT_MAP=7,
	LT_DATABASE=8,
	LT_MTEXT=9,
	LT_POLITICALDIVISION=10,
	LT_BARCODE=11,
	LT_VLINE_CONTROL=12,
	LT_HLINE_CONTROL=13
}objectType;


#endif

